import type { RecommendationPerfume } from '@harumnesia/shared';

export const fixtureDataset: RecommendationPerfume[] = [
  {
    id: 'local-amber',
    name: 'Local Amber',
    brand: 'Nusantara',
    market: 'local',
    gender: 'women',
    concentration: 'EDP',
    price: { amount: 450_000, currency: 'IDR' },
    notes: {
      top: ['bergamot'],
      middle: ['jasmine'],
      base: ['vanilla', 'amber'],
    },
    accords: [],
    occasion: ['night'],
  },
  {
    id: 'local-amber-twin',
    name: 'Local Amber Twin',
    brand: 'Nusantara',
    market: 'local',
    gender: 'women',
    concentration: 'EDP',
    price: { amount: 500_000, currency: 'IDR' },
    notes: {
      top: ['bergamot'],
      middle: ['jasmine'],
      base: ['vanilla', 'amber'],
    },
    accords: [],
    occasion: ['night'],
  },
  {
    id: 'local-citrus',
    name: 'Local Citrus',
    brand: 'Khatulistiwa',
    market: 'local',
    gender: 'men',
    concentration: 'EDT',
    price: { amount: 300_000, currency: 'IDR' },
    notes: {
      top: ['lemon'],
      middle: ['neroli'],
      base: ['musk'],
    },
    accords: [],
    occasion: ['daytime'],
  },
  {
    id: 'international-woody',
    name: 'International Woody',
    brand: 'Atlas',
    market: 'international',
    gender: 'unisex',
    concentration: null,
    price: null,
    notes: {
      top: ['bergamot'],
      middle: ['iris'],
      base: ['vanilla'],
    },
    accords: ['woody', 'sweet'],
    occasion: [],
  },
  {
    id: 'international-floral',
    name: 'International Floral',
    brand: 'Atlas',
    market: 'international',
    gender: 'women',
    concentration: null,
    price: null,
    notes: {
      top: ['rose'],
      middle: ['jasmine'],
      base: ['musk'],
    },
    accords: ['floral', 'powdery'],
    occasion: [],
  },
  {
    id: 'international-unknown',
    name: 'International Unknown',
    brand: 'Archive',
    market: 'international',
    gender: 'unknown',
    concentration: null,
    price: null,
    notes: {
      top: [],
      middle: [],
      base: ['cedar'],
    },
    accords: ['woody'],
    occasion: [],
  },
];

export const missingnessDataset: RecommendationPerfume[] = [
  {
    id: 'international-sparse',
    name: 'International Sparse',
    brand: 'Atlas',
    market: 'international',
    gender: 'unisex',
    concentration: null,
    price: null,
    notes: { top: ['vanilla'], middle: [], base: [] },
    accords: ['woody'],
    occasion: [],
  },
  {
    id: 'local-complete',
    name: 'Local Complete',
    brand: 'Nusantara',
    market: 'local',
    gender: 'unisex',
    concentration: 'EDP',
    price: { amount: 400_000, currency: 'IDR' },
    notes: { top: ['vanilla'], middle: [], base: [] },
    accords: [],
    occasion: ['night'],
  },
];
